id: I9B574C71
legacy_id: P009325
ocr_import_info:
  bdrc_scan_id: W5JW4
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T18:30:47'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:07:13.280940+00:00'
last_modified: 2022-09-04 11:08:00.058303
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W5JW4
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW5JW4
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: Miscellaneous Notes on Gampopa
  author: Herbert V. Günther
statistics:
  ocr_word_mean_confidence_index: 0.5152090611129236
  ocr_word_median_confidence_index: 0.44999998807907104
quality: null
bases:
  I1KG15553:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG15553
      total_pages: 1196
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG15553.txt
    statistics:
      ocr_word_median_confidence_index: 0.44999998807907104
      ocr_word_mean_confidence_index: 0.5152090611129236
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
