id: P009325
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W5JW4
  title: མི
  author: ''
  volumes:
    58b63d07d6444ff4bd5498c1a69377d8:
      image_group_id: I1KG15553
      title: ''
      volume_number: 1
      total_pages: 1196
      base_file: v001.txt
